version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: job_queue_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_queue_api
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - JWT_SECRET=production-secure-key-123
    depends_on:
      - redis
    restart: unless-stopped

  workers:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: job_queue_workers
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=production-secure-key-123
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

volumes:
  redis_data:
    driver: local
